# Generated by Django 6.0.2 on 2026-02-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_genre'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
